export const items = {
    root: {
      index: 'root',
      canMove: true,
      isFolder: true,
      children: ['child1', 'child2'],
      data: 'Root item',
      canRename: true,
    },
    child1: {
      index: 'child1',
      canMove: true,
      isFolder: true,
      children: [],
      data: 'Child item 10',
      canRename: true,
    },
    child2: {
      index: 'child2',
      canMove: true,
      isFolder: true,
      children: ['child3', 'child4'],
      data: 'Child item 2',
      canRename: true,
    },
    child3: {
      index: 'child3',
      canMove: true,
      isFolder: false,
      children: [],
      data: 'Child item 3',
      canRename: true,
    },
  };

  export const HesabMoeein = [
    {
      "$id": "1",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 1,
      "HesabMoeeinCode": "111001",
      "HesabMoeeinTitle": "صندوق ریالی",
      "HesabKolID": 1,
      "HesabKolCode": "1110",
      "HesabKolTitle": "موجودی نقد وبانک",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "2",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 2,
      "HesabMoeeinCode": "111002",
      "HesabMoeeinTitle": "صندوق ارزی",
      "HesabKolID": 1,
      "HesabKolCode": "1110",
      "HesabKolTitle": "موجودی نقد وبانک",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "3",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 3,
      "HesabMoeeinCode": "111003",
      "HesabMoeeinTitle": "تنخواه گردانهای ریالی",
      "HesabKolID": 1,
      "HesabKolCode": "1110",
      "HesabKolTitle": "موجودی نقد وبانک",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "4",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 4,
      "HesabMoeeinCode": "111004",
      "HesabMoeeinTitle": "تنخواه گردانهای ارزی",
      "HesabKolID": 1,
      "HesabKolCode": "1110",
      "HesabKolTitle": "موجودی نقد وبانک",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "5",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 5,
      "HesabMoeeinCode": "111005",
      "HesabMoeeinTitle": "موجودی بانکهای ریالی",
      "HesabKolID": 1,
      "HesabKolCode": "1110",
      "HesabKolTitle": "موجودی نقد وبانک",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "6",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 6,
      "HesabMoeeinCode": "111006",
      "HesabMoeeinTitle": "موجودی بانکهای ارزی",
      "HesabKolID": 1,
      "HesabKolCode": "1110",
      "HesabKolTitle": "موجودی نقد وبانک",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "7",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 7,
      "HesabMoeeinCode": "111007",
      "HesabMoeeinTitle": "موجودی کارت خوان ریالی",
      "HesabKolID": 1,
      "HesabKolCode": "1110",
      "HesabKolTitle": "موجودی نقد وبانک",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "8",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 8,
      "HesabMoeeinCode": "111008",
      "HesabMoeeinTitle": "موجودی کارت خوان ارزی",
      "HesabKolID": 1,
      "HesabKolCode": "1110",
      "HesabKolTitle": "موجودی نقد وبانک",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "9",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 9,
      "HesabMoeeinCode": "111009",
      "HesabMoeeinTitle": "وجوه در راه",
      "HesabKolID": 1,
      "HesabKolCode": "1110",
      "HesabKolTitle": "موجودی نقد وبانک",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "10",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 10,
      "HesabMoeeinCode": "111010",
      "HesabMoeeinTitle": "موجودی واریز نامه های ارزی",
      "HesabKolID": 1,
      "HesabKolCode": "1110",
      "HesabKolTitle": "موجودی نقد وبانک",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "11",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 11,
      "HesabMoeeinCode": "111101",
      "HesabMoeeinTitle": "سپرده های گمرکی",
      "HesabKolID": 2,
      "HesabKolCode": "1111",
      "HesabKolTitle": "سپرده های کوتاه مدت",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "12",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 12,
      "HesabMoeeinCode": "111102",
      "HesabMoeeinTitle": "سپرده ضمانت نامه های بانکی",
      "HesabKolID": 2,
      "HesabKolCode": "1111",
      "HesabKolTitle": "سپرده های کوتاه مدت",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "13",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 13,
      "HesabMoeeinCode": "111103",
      "HesabMoeeinTitle": "سایر سپرده ها",
      "HesabKolID": 2,
      "HesabKolCode": "1111",
      "HesabKolTitle": "سپرده های کوتاه مدت",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "14",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 14,
      "HesabMoeeinCode": "111201",
      "HesabMoeeinTitle": "حسابهای دریافتنی",
      "HesabKolID": 3,
      "HesabKolCode": "1112",
      "HesabKolTitle": "حسابهاو اسناد دریافتنی",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "15",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 15,
      "HesabMoeeinCode": "111202",
      "HesabMoeeinTitle": "چکهای دریافتنی نزد صندوق",
      "HesabKolID": 3,
      "HesabKolCode": "1112",
      "HesabKolTitle": "حسابهاو اسناد دریافتنی",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "16",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 16,
      "HesabMoeeinCode": "111203",
      "HesabMoeeinTitle": "چکهای در جریان وصول",
      "HesabKolID": 3,
      "HesabKolCode": "1112",
      "HesabKolTitle": "حسابهاو اسناد دریافتنی",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "17",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 17,
      "HesabMoeeinCode": "111205",
      "HesabMoeeinTitle": "ذخیره مطالبات مشکوک الوصول",
      "HesabKolID": 3,
      "HesabKolCode": "1112",
      "HesabKolTitle": "حسابهاو اسناد دریافتنی",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "18",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 18,
      "HesabMoeeinCode": "111206",
      "HesabMoeeinTitle": "اسناد واخواست شده",
      "HesabKolID": 3,
      "HesabKolCode": "1112",
      "HesabKolTitle": "حسابهاو اسناد دریافتنی",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "19",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 19,
      "HesabMoeeinCode": "111301",
      "HesabMoeeinTitle": "مساعده حقوق",
      "HesabKolID": 4,
      "HesabKolCode": "1113",
      "HesabKolTitle": "سایر حسابهای دریافتنی",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "20",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 20,
      "HesabMoeeinCode": "111302",
      "HesabMoeeinTitle": "وام کارکنان",
      "HesabKolID": 4,
      "HesabKolCode": "1113",
      "HesabKolTitle": "سایر حسابهای دریافتنی",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "21",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 21,
      "HesabMoeeinCode": "111306",
      "HesabMoeeinTitle": "خسارات قابل دریافت ازبیمه",
      "HesabKolID": 4,
      "HesabKolCode": "1113",
      "HesabKolTitle": "سایر حسابهای دریافتنی",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "22",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 22,
      "HesabMoeeinCode": "111311",
      "HesabMoeeinTitle": "سایر حسابها واسناد دریافتنی",
      "HesabKolID": 4,
      "HesabKolCode": "1113",
      "HesabKolTitle": "سایر حسابهای دریافتنی",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "23",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 23,
      "HesabMoeeinCode": "111504",
      "HesabMoeeinTitle": "موجودی انبار",
      "HesabKolID": 5,
      "HesabKolCode": "1115",
      "HesabKolTitle": "موجودی انبارها",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "24",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 24,
      "HesabMoeeinCode": "111507",
      "HesabMoeeinTitle": "واسط کرایه حمل موجودی",
      "HesabKolID": 5,
      "HesabKolCode": "1115",
      "HesabKolTitle": "موجودی انبارها",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "25",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 25,
      "HesabMoeeinCode": "111601",
      "HesabMoeeinTitle": "بهای اصلی سفارش",
      "HesabKolID": 6,
      "HesabKolCode": "1116",
      "HesabKolTitle": "سفارشات واقلام در راه",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "26",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 26,
      "HesabMoeeinCode": "111602",
      "HesabMoeeinTitle": "هزینه های ثبت سفارش",
      "HesabKolID": 6,
      "HesabKolCode": "1116",
      "HesabKolTitle": "سفارشات واقلام در راه",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "27",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 27,
      "HesabMoeeinCode": "111603",
      "HesabMoeeinTitle": "هزینه های بیمه سفارش",
      "HesabKolID": 6,
      "HesabKolCode": "1116",
      "HesabKolTitle": "سفارشات واقلام در راه",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "28",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 28,
      "HesabMoeeinCode": "111604",
      "HesabMoeeinTitle": "هزینه های بانکی سفارش",
      "HesabKolID": 6,
      "HesabKolCode": "1116",
      "HesabKolTitle": "سفارشات واقلام در راه",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "29",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 29,
      "HesabMoeeinCode": "111605",
      "HesabMoeeinTitle": "هزینه های گمرکی",
      "HesabKolID": 6,
      "HesabKolCode": "1116",
      "HesabKolTitle": "سفارشات واقلام در راه",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "30",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 30,
      "HesabMoeeinCode": "111606",
      "HesabMoeeinTitle": "حقوق وعوارض بندری",
      "HesabKolID": 6,
      "HesabKolCode": "1116",
      "HesabKolTitle": "سفارشات واقلام در راه",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "31",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 31,
      "HesabMoeeinCode": "111607",
      "HesabMoeeinTitle": "هزینه بازرسی",
      "HesabKolID": 6,
      "HesabKolCode": "1116",
      "HesabKolTitle": "سفارشات واقلام در راه",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "32",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 32,
      "HesabMoeeinCode": "111608",
      "HesabMoeeinTitle": "هزینه حق العمل ترخیص",
      "HesabKolID": 6,
      "HesabKolCode": "1116",
      "HesabKolTitle": "سفارشات واقلام در راه",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "33",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 33,
      "HesabMoeeinCode": "111609",
      "HesabMoeeinTitle": "هزینه حمل",
      "HesabKolID": 6,
      "HesabKolCode": "1116",
      "HesabKolTitle": "سفارشات واقلام در راه",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "34",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 34,
      "HesabMoeeinCode": "111610",
      "HesabMoeeinTitle": "سایر هزینه ها",
      "HesabKolID": 6,
      "HesabKolCode": "1116",
      "HesabKolTitle": "سفارشات واقلام در راه",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "35",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 35,
      "HesabMoeeinCode": "111611",
      "HesabMoeeinTitle": "هزینه قبل از گشایش اعتبار",
      "HesabKolID": 6,
      "HesabKolCode": "1116",
      "HesabKolTitle": "سفارشات واقلام در راه",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "36",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 36,
      "HesabMoeeinCode": "111701",
      "HesabMoeeinTitle": "پیش پرداخت هزینه های جاری",
      "HesabKolID": 7,
      "HesabKolCode": "1117",
      "HesabKolTitle": "پیش پرداختها",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "37",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 37,
      "HesabMoeeinCode": "111703",
      "HesabMoeeinTitle": "پیش پرداخت بیمه دارائیها",
      "HesabKolID": 7,
      "HesabKolCode": "1117",
      "HesabKolTitle": "پیش پرداختها",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "38",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 38,
      "HesabMoeeinCode": "111705",
      "HesabMoeeinTitle": "پیش پرداخت مالیات",
      "HesabKolID": 7,
      "HesabKolCode": "1117",
      "HesabKolTitle": "پیش پرداختها",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "39",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 39,
      "HesabMoeeinCode": "111706",
      "HesabMoeeinTitle": "پیش پرداخت اجاره",
      "HesabKolID": 7,
      "HesabKolCode": "1117",
      "HesabKolTitle": "پیش پرداختها",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "40",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 40,
      "HesabMoeeinCode": "111707",
      "HesabMoeeinTitle": "پیش پرداخت هزینه سود وکارمزدوامها",
      "HesabKolID": 7,
      "HesabKolCode": "1117",
      "HesabKolTitle": "پیش پرداختها",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "41",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 41,
      "HesabMoeeinCode": "111709",
      "HesabMoeeinTitle": "پیش پرداخت مالیات ارزش افزوده",
      "HesabKolID": 7,
      "HesabKolCode": "1117",
      "HesabKolTitle": "پیش پرداختها",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "42",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 42,
      "HesabMoeeinCode": "111710",
      "HesabMoeeinTitle": "پیش پرداخت عوارض ارزش افزوده",
      "HesabKolID": 7,
      "HesabKolCode": "1117",
      "HesabKolTitle": "پیش پرداختها",
      "GoroohHesabID": 1,
      "GoroohHesabCode": "11",
      "GoroohHesabTitle": "داراییهای جاری"
    },
    {
      "$id": "43",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 43,
      "HesabMoeeinCode": "121001",
      "HesabMoeeinTitle": "زمین",
      "HesabKolID": 8,
      "HesabKolCode": "1210",
      "HesabKolTitle": "دارایی های ثابت",
      "GoroohHesabID": 2,
      "GoroohHesabCode": "12",
      "GoroohHesabTitle": "داراییهای غیرجاری"
    },
    {
      "$id": "44",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 44,
      "HesabMoeeinCode": "121002",
      "HesabMoeeinTitle": "ساختمانها",
      "HesabKolID": 8,
      "HesabKolCode": "1210",
      "HesabKolTitle": "دارایی های ثابت",
      "GoroohHesabID": 2,
      "GoroohHesabCode": "12",
      "GoroohHesabTitle": "داراییهای غیرجاری"
    },
    {
      "$id": "45",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 45,
      "HesabMoeeinCode": "121003",
      "HesabMoeeinTitle": "وسائط نقلیه",
      "HesabKolID": 8,
      "HesabKolCode": "1210",
      "HesabKolTitle": "دارایی های ثابت",
      "GoroohHesabID": 2,
      "GoroohHesabCode": "12",
      "GoroohHesabTitle": "داراییهای غیرجاری"
    },
    {
      "$id": "46",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 46,
      "HesabMoeeinCode": "121004",
      "HesabMoeeinTitle": "اثاثیه ومنصوبات",
      "HesabKolID": 8,
      "HesabKolCode": "1210",
      "HesabKolTitle": "دارایی های ثابت",
      "GoroohHesabID": 2,
      "GoroohHesabCode": "12",
      "GoroohHesabTitle": "داراییهای غیرجاری"
    },
    {
      "$id": "47",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 47,
      "HesabMoeeinCode": "121101",
      "HesabMoeeinTitle": "استهلاک انباشته ساختمانها",
      "HesabKolID": 9,
      "HesabKolCode": "1211",
      "HesabKolTitle": "استهلاک انباشته",
      "GoroohHesabID": 2,
      "GoroohHesabCode": "12",
      "GoroohHesabTitle": "داراییهای غیرجاری"
    },
    {
      "$id": "48",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 48,
      "HesabMoeeinCode": "121102",
      "HesabMoeeinTitle": "استهلاک انباشته وسائط نقلیه",
      "HesabKolID": 9,
      "HesabKolCode": "1211",
      "HesabKolTitle": "استهلاک انباشته",
      "GoroohHesabID": 2,
      "GoroohHesabCode": "12",
      "GoroohHesabTitle": "داراییهای غیرجاری"
    },
    {
      "$id": "49",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 49,
      "HesabMoeeinCode": "121103",
      "HesabMoeeinTitle": "استهلاک انباشته اثاثیه و منصوبات",
      "HesabKolID": 9,
      "HesabKolCode": "1211",
      "HesabKolTitle": "استهلاک انباشته",
      "GoroohHesabID": 2,
      "GoroohHesabCode": "12",
      "GoroohHesabTitle": "داراییهای غیرجاری"
    },
    {
      "$id": "50",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 50,
      "HesabMoeeinCode": "121302",
      "HesabMoeeinTitle": "سپرده های بلند مدت نزد بانکها",
      "HesabKolID": 10,
      "HesabKolCode": "1213",
      "HesabKolTitle": "سپرده هاو مطالبات بلند مدت",
      "GoroohHesabID": 2,
      "GoroohHesabCode": "12",
      "GoroohHesabTitle": "داراییهای غیرجاری"
    },
    {
      "$id": "51",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 51,
      "HesabMoeeinCode": "121401",
      "HesabMoeeinTitle": "حق الامتیازها و ودایع",
      "HesabKolID": 11,
      "HesabKolCode": "1214",
      "HesabKolTitle": "سایر دارائیها",
      "GoroohHesabID": 2,
      "GoroohHesabCode": "12",
      "GoroohHesabTitle": "داراییهای غیرجاری"
    },
    {
      "$id": "52",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 52,
      "HesabMoeeinCode": "121408",
      "HesabMoeeinTitle": "نرم افزار ها",
      "HesabKolID": 11,
      "HesabKolCode": "1214",
      "HesabKolTitle": "سایر دارائیها",
      "GoroohHesabID": 2,
      "GoroohHesabCode": "12",
      "GoroohHesabTitle": "داراییهای غیرجاری"
    },
    {
      "$id": "53",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 53,
      "HesabMoeeinCode": "211001",
      "HesabMoeeinTitle": "حسابهای پرداختنی",
      "HesabKolID": 12,
      "HesabKolCode": "2110",
      "HesabKolTitle": "حسابها و اسناد پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "54",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 54,
      "HesabMoeeinCode": "211003",
      "HesabMoeeinTitle": "اسناد پرداختنی ریالی",
      "HesabKolID": 12,
      "HesabKolCode": "2110",
      "HesabKolTitle": "حسابها و اسناد پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "55",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 55,
      "HesabMoeeinCode": "211004",
      "HesabMoeeinTitle": "اسنادپرداختنی ارزی",
      "HesabKolID": 12,
      "HesabKolCode": "2110",
      "HesabKolTitle": "حسابها و اسناد پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "56",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 56,
      "HesabMoeeinCode": "211201",
      "HesabMoeeinTitle": "مالیات بر در آمدشرکت",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "57",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 57,
      "HesabMoeeinCode": "211202",
      "HesabMoeeinTitle": "مالیات حقوق ودستمزد کارکنان",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "58",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 58,
      "HesabMoeeinCode": "211203",
      "HesabMoeeinTitle": "مالیات تکلیفی اشخاص ثالث",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "59",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 59,
      "HesabMoeeinCode": "211204",
      "HesabMoeeinTitle": "حق بیمه پرداختنی کارکنان - سازمان تامین اجتماعی",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "60",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 60,
      "HesabMoeeinCode": "211205",
      "HesabMoeeinTitle": "حق بیمه پرداختنی اشخاص ثالت - سازمان تامین اجتماعی",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "61",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 61,
      "HesabMoeeinCode": "211206",
      "HesabMoeeinTitle": "حقوق ودستمزد پرداختنی",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "62",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 62,
      "HesabMoeeinCode": "211207",
      "HesabMoeeinTitle": "عیدی وپاداش پرداختنی",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "63",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 63,
      "HesabMoeeinCode": "211209",
      "HesabMoeeinTitle": "هزینه های پرداختنی",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "64",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 64,
      "HesabMoeeinCode": "211210",
      "HesabMoeeinTitle": "روند حقوق",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "65",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 65,
      "HesabMoeeinCode": "211211",
      "HesabMoeeinTitle": "مالیات ارزش افزوده پرداختی",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "66",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 66,
      "HesabMoeeinCode": "211212",
      "HesabMoeeinTitle": "عوارض ارزش افزوده پرداختی",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "67",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 67,
      "HesabMoeeinCode": "211213",
      "HesabMoeeinTitle": "سایر حسابهای پرداختنی",
      "HesabKolID": 13,
      "HesabKolCode": "2112",
      "HesabKolTitle": "سایر حسابهای پرداختنی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "68",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 68,
      "HesabMoeeinCode": "211302",
      "HesabMoeeinTitle": "سپرده های دریافتی حسن انجام کار",
      "HesabKolID": 14,
      "HesabKolCode": "2113",
      "HesabKolTitle": "سپرده های دریافتی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "69",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 69,
      "HesabMoeeinCode": "211303",
      "HesabMoeeinTitle": "سایر سپرده های دریافتی",
      "HesabKolID": 14,
      "HesabKolCode": "2113",
      "HesabKolTitle": "سپرده های دریافتی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "70",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 70,
      "HesabMoeeinCode": "211401",
      "HesabMoeeinTitle": "پیش دریافت فروش",
      "HesabKolID": 15,
      "HesabKolCode": "2114",
      "HesabKolTitle": "پیش دریافتها",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "71",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 71,
      "HesabMoeeinCode": "211402",
      "HesabMoeeinTitle": "سایر پیش دریافتها",
      "HesabKolID": 15,
      "HesabKolCode": "2114",
      "HesabKolTitle": "پیش دریافتها",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "72",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 72,
      "HesabMoeeinCode": "211501",
      "HesabMoeeinTitle": "ذخیره مالیات",
      "HesabKolID": 16,
      "HesabKolCode": "2115",
      "HesabKolTitle": "ذخیره مالیات",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "73",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 73,
      "HesabMoeeinCode": "211601",
      "HesabMoeeinTitle": "وامهای پرداختی کوتاه مدت - فروش اقساطی",
      "HesabKolID": 17,
      "HesabKolCode": "2116",
      "HesabKolTitle": "تسهیلات و اعتبارات مالی دریافتی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "74",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 74,
      "HesabMoeeinCode": "211602",
      "HesabMoeeinTitle": "وامهای دریافتی کوتاه مدت - سلف",
      "HesabKolID": 17,
      "HesabKolCode": "2116",
      "HesabKolTitle": "تسهیلات و اعتبارات مالی دریافتی",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "75",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 75,
      "HesabMoeeinCode": "211701",
      "HesabMoeeinTitle": "ذخیره مرخصی استفاده  نشده",
      "HesabKolID": 18,
      "HesabKolCode": "2117",
      "HesabKolTitle": "سایر ذخایر",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "76",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 76,
      "HesabMoeeinCode": "211702",
      "HesabMoeeinTitle": "سایر ذخایر",
      "HesabKolID": 18,
      "HesabKolCode": "2117",
      "HesabKolTitle": "سایر ذخایر",
      "GoroohHesabID": 3,
      "GoroohHesabCode": "21",
      "GoroohHesabTitle": "بدهیهای جاری"
    },
    {
      "$id": "77",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 77,
      "HesabMoeeinCode": "221001",
      "HesabMoeeinTitle": "حسابهای پرداختنی بلند مدت",
      "HesabKolID": 19,
      "HesabKolCode": "2210",
      "HesabKolTitle": "حسابها و اسناد پرداختنی بلند مدت",
      "GoroohHesabID": 4,
      "GoroohHesabCode": "22",
      "GoroohHesabTitle": "بدهیهای غیر جاری"
    },
    {
      "$id": "78",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 78,
      "HesabMoeeinCode": "221002",
      "HesabMoeeinTitle": "اسنادپرداختنی بلند مدت ریالی",
      "HesabKolID": 19,
      "HesabKolCode": "2210",
      "HesabKolTitle": "حسابها و اسناد پرداختنی بلند مدت",
      "GoroohHesabID": 4,
      "GoroohHesabCode": "22",
      "GoroohHesabTitle": "بدهیهای غیر جاری"
    },
    {
      "$id": "79",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 79,
      "HesabMoeeinCode": "221003",
      "HesabMoeeinTitle": "اسنادپرداختنی بلند مدت ارزی",
      "HesabKolID": 19,
      "HesabKolCode": "2210",
      "HesabKolTitle": "حسابها و اسناد پرداختنی بلند مدت",
      "GoroohHesabID": 4,
      "GoroohHesabCode": "22",
      "GoroohHesabTitle": "بدهیهای غیر جاری"
    },
    {
      "$id": "80",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 80,
      "HesabMoeeinCode": "221101",
      "HesabMoeeinTitle": "وامهای پرداختنی بلند مدت - فروش اقساطی",
      "HesabKolID": 20,
      "HesabKolCode": "2211",
      "HesabKolTitle": "تسهیلات مالی دریافتی بلند مدت",
      "GoroohHesabID": 4,
      "GoroohHesabCode": "22",
      "GoroohHesabTitle": "بدهیهای غیر جاری"
    },
    {
      "$id": "81",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 81,
      "HesabMoeeinCode": "221102",
      "HesabMoeeinTitle": "وامهای پرداختنی بلند مدت - سلف",
      "HesabKolID": 20,
      "HesabKolCode": "2211",
      "HesabKolTitle": "تسهیلات مالی دریافتی بلند مدت",
      "GoroohHesabID": 4,
      "GoroohHesabCode": "22",
      "GoroohHesabTitle": "بدهیهای غیر جاری"
    },
    {
      "$id": "82",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 82,
      "HesabMoeeinCode": "221201",
      "HesabMoeeinTitle": "ذخیره مزایای پایان خدمت کارکنان",
      "HesabKolID": 21,
      "HesabKolCode": "2212",
      "HesabKolTitle": "ذخیره مزایای پایان خدمت کارکنان",
      "GoroohHesabID": 4,
      "GoroohHesabCode": "22",
      "GoroohHesabTitle": "بدهیهای غیر جاری"
    },
    {
      "$id": "83",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 83,
      "HesabMoeeinCode": "311001",
      "HesabMoeeinTitle": "سرمایه",
      "HesabKolID": 22,
      "HesabKolCode": "3110",
      "HesabKolTitle": "سرمایه",
      "GoroohHesabID": 5,
      "GoroohHesabCode": "31",
      "GoroohHesabTitle": "حقوق صاحبان سهام"
    },
    {
      "$id": "84",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 84,
      "HesabMoeeinCode": "311101",
      "HesabMoeeinTitle": "اندوخته قانونی",
      "HesabKolID": 23,
      "HesabKolCode": "3111",
      "HesabKolTitle": "اندوخته قانونی",
      "GoroohHesabID": 5,
      "GoroohHesabCode": "31",
      "GoroohHesabTitle": "حقوق صاحبان سهام"
    },
    {
      "$id": "85",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 85,
      "HesabMoeeinCode": "311201",
      "HesabMoeeinTitle": "سود (زیان ) انباشته",
      "HesabKolID": 24,
      "HesabKolCode": "3112",
      "HesabKolTitle": "سود (زیان ) انباشته",
      "GoroohHesabID": 5,
      "GoroohHesabCode": "31",
      "GoroohHesabTitle": "حقوق صاحبان سهام"
    },
    {
      "$id": "86",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 86,
      "HesabMoeeinCode": "311301",
      "HesabMoeeinTitle": "سود (زیان ) جاری",
      "HesabKolID": 25,
      "HesabKolCode": "3113",
      "HesabKolTitle": "سود (زیان ) جاری",
      "GoroohHesabID": 5,
      "GoroohHesabCode": "31",
      "GoroohHesabTitle": "حقوق صاحبان سهام"
    },
    {
      "$id": "87",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 87,
      "HesabMoeeinCode": "411001",
      "HesabMoeeinTitle": "فروش  داخلی",
      "HesabKolID": 26,
      "HesabKolCode": "4110",
      "HesabKolTitle": "فروش",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "88",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 88,
      "HesabMoeeinCode": "411002",
      "HesabMoeeinTitle": "فروش  خارجی",
      "HesabKolID": 26,
      "HesabKolCode": "4110",
      "HesabKolTitle": "فروش",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "89",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 89,
      "HesabMoeeinCode": "411003",
      "HesabMoeeinTitle": "فروش خدمات",
      "HesabKolID": 26,
      "HesabKolCode": "4110",
      "HesabKolTitle": "فروش",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "90",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 90,
      "HesabMoeeinCode": "411101",
      "HesabMoeeinTitle": "برگشت از فروش  داخلی",
      "HesabKolID": 27,
      "HesabKolCode": "4111",
      "HesabKolTitle": "برگشت از فروش وتخفیفات",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "91",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 91,
      "HesabMoeeinCode": "411102",
      "HesabMoeeinTitle": "برگشت از فروش  خارجی",
      "HesabKolID": 27,
      "HesabKolCode": "4111",
      "HesabKolTitle": "برگشت از فروش وتخفیفات",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "92",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 92,
      "HesabMoeeinCode": "411103",
      "HesabMoeeinTitle": "برگشت از فروش خدمات",
      "HesabKolID": 27,
      "HesabKolCode": "4111",
      "HesabKolTitle": "برگشت از فروش وتخفیفات",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "93",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 93,
      "HesabMoeeinCode": "411111",
      "HesabMoeeinTitle": "تخفیفات فروش داخلی",
      "HesabKolID": 27,
      "HesabKolCode": "4111",
      "HesabKolTitle": "برگشت از فروش وتخفیفات",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "94",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 94,
      "HesabMoeeinCode": "411112",
      "HesabMoeeinTitle": "تخفیفات فروش خارجی",
      "HesabKolID": 27,
      "HesabKolCode": "4111",
      "HesabKolTitle": "برگشت از فروش وتخفیفات",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "95",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 95,
      "HesabMoeeinCode": "411113",
      "HesabMoeeinTitle": "تخفیفات فروش خدمات",
      "HesabKolID": 27,
      "HesabKolCode": "4111",
      "HesabKolTitle": "برگشت از فروش وتخفیفات",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "96",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 96,
      "HesabMoeeinCode": "411201",
      "HesabMoeeinTitle": "سود و زیان فروش ضایعات",
      "HesabKolID": 28,
      "HesabKolCode": "4112",
      "HesabKolTitle": "سایر درآمد ها و هزینه ها",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "97",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 97,
      "HesabMoeeinCode": "411202",
      "HesabMoeeinTitle": "سایر هزینه ها و درآمدها",
      "HesabKolID": 28,
      "HesabKolCode": "4112",
      "HesabKolTitle": "سایر درآمد ها و هزینه ها",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "98",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 98,
      "HesabMoeeinCode": "411205",
      "HesabMoeeinTitle": "تخفیفات نقدی فروش",
      "HesabKolID": 28,
      "HesabKolCode": "4112",
      "HesabKolTitle": "سایر درآمد ها و هزینه ها",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "99",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 99,
      "HesabMoeeinCode": "411206",
      "HesabMoeeinTitle": "تخفیفات نقدی خرید",
      "HesabKolID": 28,
      "HesabKolCode": "4112",
      "HesabKolTitle": "سایر درآمد ها و هزینه ها",
      "GoroohHesabID": 6,
      "GoroohHesabCode": "41",
      "GoroohHesabTitle": "فروش و درآمدها"
    },
    {
      "$id": "100",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 100,
      "HesabMoeeinCode": "511001",
      "HesabMoeeinTitle": "بهای تمام شده کالای فروش رفته داخلی",
      "HesabKolID": 29,
      "HesabKolCode": "5110",
      "HesabKolTitle": "بهای تمام شده کالای فروش رفته",
      "GoroohHesabID": 7,
      "GoroohHesabCode": "51",
      "GoroohHesabTitle": "بهای تمام شده کالای فروش رفته"
    },
    {
      "$id": "101",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 101,
      "HesabMoeeinCode": "511002",
      "HesabMoeeinTitle": "بهای تمام شده کالای فروش رفته خارجی",
      "HesabKolID": 29,
      "HesabKolCode": "5110",
      "HesabKolTitle": "بهای تمام شده کالای فروش رفته",
      "GoroohHesabID": 7,
      "GoroohHesabCode": "51",
      "GoroohHesabTitle": "بهای تمام شده کالای فروش رفته"
    },
    {
      "$id": "102",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 102,
      "HesabMoeeinCode": "511009",
      "HesabMoeeinTitle": "بهای تمام شده خدمات",
      "HesabKolID": 29,
      "HesabKolCode": "5110",
      "HesabKolTitle": "بهای تمام شده کالای فروش رفته",
      "GoroohHesabID": 7,
      "GoroohHesabCode": "51",
      "GoroohHesabTitle": "بهای تمام شده کالای فروش رفته"
    },
    {
      "$id": "103",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 103,
      "HesabMoeeinCode": "611001",
      "HesabMoeeinTitle": "حقوق پایه",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "104",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 104,
      "HesabMoeeinCode": "611002",
      "HesabMoeeinTitle": "اضافه کاری",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "105",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 105,
      "HesabMoeeinCode": "611003",
      "HesabMoeeinTitle": "حق شیفت وشبکاری",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "106",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 106,
      "HesabMoeeinCode": "611004",
      "HesabMoeeinTitle": "حق نوبت کاری",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "107",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 107,
      "HesabMoeeinCode": "611005",
      "HesabMoeeinTitle": "فوق العاده مسکن وخواروبار",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "108",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 108,
      "HesabMoeeinCode": "611006",
      "HesabMoeeinTitle": "حق اولاد",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "109",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 109,
      "HesabMoeeinCode": "611007",
      "HesabMoeeinTitle": "عیدی وپاداش",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "110",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 110,
      "HesabMoeeinCode": "611008",
      "HesabMoeeinTitle": "بیمه سهم کارفرما",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "111",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 111,
      "HesabMoeeinCode": "611009",
      "HesabMoeeinTitle": "بازخرید سنوات خدمت کارکنان",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "112",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 112,
      "HesabMoeeinCode": "611010",
      "HesabMoeeinTitle": "مرخصی استفاده نشده",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "113",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 113,
      "HesabMoeeinCode": "611011",
      "HesabMoeeinTitle": "بیمه بیکاری",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "114",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 114,
      "HesabMoeeinCode": "611013",
      "HesabMoeeinTitle": "حقوق و مزایای متفرقه",
      "HesabKolID": 30,
      "HesabKolCode": "6110",
      "HesabKolTitle": "هزینه های  حقوق ودستمزد",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "115",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 115,
      "HesabMoeeinCode": "611101",
      "HesabMoeeinTitle": "سفر ، اقامت وفوق العاده ماموریت",
      "HesabKolID": 31,
      "HesabKolCode": "6111",
      "HesabKolTitle": "هزینه های کارکنان",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "116",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 116,
      "HesabMoeeinCode": "611102",
      "HesabMoeeinTitle": "ایاب وذهاب",
      "HesabKolID": 31,
      "HesabKolCode": "6111",
      "HesabKolTitle": "هزینه های کارکنان",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "117",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 117,
      "HesabMoeeinCode": "611103",
      "HesabMoeeinTitle": "سایر هزینه های کارکنان",
      "HesabKolID": 31,
      "HesabKolCode": "6111",
      "HesabKolTitle": "هزینه های کارکنان",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "118",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 118,
      "HesabMoeeinCode": "611201",
      "HesabMoeeinTitle": "تعمیر ونگهداری",
      "HesabKolID": 32,
      "HesabKolCode": "6112",
      "HesabKolTitle": "هزینه های عملیاتی",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "119",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 119,
      "HesabMoeeinCode": "611202",
      "HesabMoeeinTitle": "هزینه آب و برق مصرفی",
      "HesabKolID": 32,
      "HesabKolCode": "6112",
      "HesabKolTitle": "هزینه های عملیاتی",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "120",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 120,
      "HesabMoeeinCode": "611203",
      "HesabMoeeinTitle": "بیمه دارائیهای ثابت",
      "HesabKolID": 32,
      "HesabKolCode": "6112",
      "HesabKolTitle": "هزینه های عملیاتی",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "121",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 121,
      "HesabMoeeinCode": "611204",
      "HesabMoeeinTitle": "بیمه موجودیها",
      "HesabKolID": 32,
      "HesabKolCode": "6112",
      "HesabKolTitle": "هزینه های عملیاتی",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "122",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 122,
      "HesabMoeeinCode": "611205",
      "HesabMoeeinTitle": "هزینه ملزومات ونوشت افزار",
      "HesabKolID": 32,
      "HesabKolCode": "6112",
      "HesabKolTitle": "هزینه های عملیاتی",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "123",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 123,
      "HesabMoeeinCode": "611206",
      "HesabMoeeinTitle": "هزینه پست وتلفن",
      "HesabKolID": 32,
      "HesabKolCode": "6112",
      "HesabKolTitle": "هزینه های عملیاتی",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "124",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 124,
      "HesabMoeeinCode": "611207",
      "HesabMoeeinTitle": "هزینه اجاره محل",
      "HesabKolID": 32,
      "HesabKolCode": "6112",
      "HesabKolTitle": "هزینه های عملیاتی",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "125",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 125,
      "HesabMoeeinCode": "611301",
      "HesabMoeeinTitle": "هزینه استهلاک ساختمان",
      "HesabKolID": 33,
      "HesabKolCode": "6113",
      "HesabKolTitle": "هزینه های استهلاک",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "126",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 126,
      "HesabMoeeinCode": "611305",
      "HesabMoeeinTitle": "هزینه استهلاک وسائط نقلیه",
      "HesabKolID": 33,
      "HesabKolCode": "6113",
      "HesabKolTitle": "هزینه های استهلاک",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "127",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 127,
      "HesabMoeeinCode": "611306",
      "HesabMoeeinTitle": "هزینه استهلاک اثاثیه و منصوبات",
      "HesabKolID": 33,
      "HesabKolCode": "6113",
      "HesabKolTitle": "هزینه های استهلاک",
      "GoroohHesabID": 8,
      "GoroohHesabCode": "61",
      "GoroohHesabTitle": "هزینه ها"
    },
    {
      "$id": "128",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 128,
      "HesabMoeeinCode": "621001",
      "HesabMoeeinTitle": "هزینه آگهی و تبلیغات",
      "HesabKolID": 34,
      "HesabKolCode": "6210",
      "HesabKolTitle": "هزینه های بازاریابی و توزیع و فروش",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "129",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 129,
      "HesabMoeeinCode": "621002",
      "HesabMoeeinTitle": "هزینه شرکت درمناقصه",
      "HesabKolID": 34,
      "HesabKolCode": "6210",
      "HesabKolTitle": "هزینه های بازاریابی و توزیع و فروش",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "130",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 130,
      "HesabMoeeinCode": "621003",
      "HesabMoeeinTitle": "هزینه های نمایشگاه",
      "HesabKolID": 34,
      "HesabKolCode": "6210",
      "HesabKolTitle": "هزینه های بازاریابی و توزیع و فروش",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "131",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 131,
      "HesabMoeeinCode": "621004",
      "HesabMoeeinTitle": "هزینه بازاریابی و پورسانت",
      "HesabKolID": 34,
      "HesabKolCode": "6210",
      "HesabKolTitle": "هزینه های بازاریابی و توزیع و فروش",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "132",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 132,
      "HesabMoeeinCode": "621005",
      "HesabMoeeinTitle": "هزینه های حمل وانبارداری",
      "HesabKolID": 34,
      "HesabKolCode": "6210",
      "HesabKolTitle": "هزینه های بازاریابی و توزیع و فروش",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "133",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 133,
      "HesabMoeeinCode": "621006",
      "HesabMoeeinTitle": "هزینه های متفرقه توزیع وفروش",
      "HesabKolID": 34,
      "HesabKolCode": "6210",
      "HesabKolTitle": "هزینه های بازاریابی و توزیع و فروش",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "134",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 134,
      "HesabMoeeinCode": "621007",
      "HesabMoeeinTitle": "هزینه های واخواست",
      "HesabKolID": 34,
      "HesabKolCode": "6210",
      "HesabKolTitle": "هزینه های بازاریابی و توزیع و فروش",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "135",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 135,
      "HesabMoeeinCode": "621008",
      "HesabMoeeinTitle": "هزینه مطالبات سوخت شده",
      "HesabKolID": 34,
      "HesabKolCode": "6210",
      "HesabKolTitle": "هزینه های بازاریابی و توزیع و فروش",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "136",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 136,
      "HesabMoeeinCode": "621101",
      "HesabMoeeinTitle": "هزینه سود وکارمزد وامها",
      "HesabKolID": 35,
      "HesabKolCode": "6211",
      "HesabKolTitle": "هزینه های مالی",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "137",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 137,
      "HesabMoeeinCode": "621102",
      "HesabMoeeinTitle": "هزینه کارمزد خدمات بانکی",
      "HesabKolID": 35,
      "HesabKolCode": "6211",
      "HesabKolTitle": "هزینه های مالی",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "138",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 138,
      "HesabMoeeinCode": "621103",
      "HesabMoeeinTitle": "هزینه جریمه دیر کرد وامها",
      "HesabKolID": 35,
      "HesabKolCode": "6211",
      "HesabKolTitle": "هزینه های مالی",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "139",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 139,
      "HesabMoeeinCode": "621104",
      "HesabMoeeinTitle": "هزینه های متفرقه مالی",
      "HesabKolID": 35,
      "HesabKolCode": "6211",
      "HesabKolTitle": "هزینه های مالی",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "140",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 140,
      "HesabMoeeinCode": "621301",
      "HesabMoeeinTitle": "سود و زیان ناشی از تسعیر ارز",
      "HesabKolID": 36,
      "HesabKolCode": "6213",
      "HesabKolTitle": "سایر هزینه ها و درآمدهای غیر عملیاتی",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "141",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 141,
      "HesabMoeeinCode": "621302",
      "HesabMoeeinTitle": "سود و زیان ناشی از فروش دارائیها",
      "HesabKolID": 36,
      "HesabKolCode": "6213",
      "HesabKolTitle": "سایر هزینه ها و درآمدهای غیر عملیاتی",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "142",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 142,
      "HesabMoeeinCode": "621307",
      "HesabMoeeinTitle": "زیان ناشی از اسقاط دارائیها",
      "HesabKolID": 36,
      "HesabKolCode": "6213",
      "HesabKolTitle": "سایر هزینه ها و درآمدهای غیر عملیاتی",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "143",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 143,
      "HesabMoeeinCode": "621308",
      "HesabMoeeinTitle": "زیان ناشی از حذف دارائیها",
      "HesabKolID": 36,
      "HesabKolCode": "6213",
      "HesabKolTitle": "سایر هزینه ها و درآمدهای غیر عملیاتی",
      "GoroohHesabID": 9,
      "GoroohHesabCode": "62",
      "GoroohHesabTitle": "سایر هزینه ها و درآمدها"
    },
    {
      "$id": "144",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 144,
      "HesabMoeeinCode": "911001",
      "HesabMoeeinTitle": "اسناد تضمینی دریافتی از کارکنان",
      "HesabKolID": 37,
      "HesabKolCode": "9110",
      "HesabKolTitle": "حسابهای انتظامی به نفع شرکت",
      "GoroohHesabID": 10,
      "GoroohHesabCode": "91",
      "GoroohHesabTitle": "حسابهای انتظامی"
    },
    {
      "$id": "145",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 145,
      "HesabMoeeinCode": "911002",
      "HesabMoeeinTitle": "سایر اسناد تضمینی به نفع شرکت",
      "HesabKolID": 37,
      "HesabKolCode": "9110",
      "HesabKolTitle": "حسابهای انتظامی به نفع شرکت",
      "GoroohHesabID": 10,
      "GoroohHesabCode": "91",
      "GoroohHesabTitle": "حسابهای انتظامی"
    },
    {
      "$id": "146",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 146,
      "HesabMoeeinCode": "911003",
      "HesabMoeeinTitle": "اسناد تضمینی تنخواه",
      "HesabKolID": 37,
      "HesabKolCode": "9110",
      "HesabKolTitle": "حسابهای انتظامی به نفع شرکت",
      "GoroohHesabID": 10,
      "GoroohHesabCode": "91",
      "GoroohHesabTitle": "حسابهای انتظامی"
    },
    {
      "$id": "147",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 147,
      "HesabMoeeinCode": "911004",
      "HesabMoeeinTitle": "موجودی ضایعات",
      "HesabKolID": 37,
      "HesabKolCode": "9110",
      "HesabKolTitle": "حسابهای انتظامی به نفع شرکت",
      "GoroohHesabID": 10,
      "GoroohHesabCode": "91",
      "GoroohHesabTitle": "حسابهای انتظامی"
    },
    {
      "$id": "148",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 148,
      "HesabMoeeinCode": "911101",
      "HesabMoeeinTitle": "ضمانت نامه های شرکت در مناقصه ومزایده",
      "HesabKolID": 38,
      "HesabKolCode": "9111",
      "HesabKolTitle": "حسابهای انتظامی به عهده شرکت",
      "GoroohHesabID": 10,
      "GoroohHesabCode": "91",
      "GoroohHesabTitle": "حسابهای انتظامی"
    },
    {
      "$id": "149",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 149,
      "HesabMoeeinCode": "911102",
      "HesabMoeeinTitle": "ضمانت نامه های حسن انجام کار",
      "HesabKolID": 38,
      "HesabKolCode": "9111",
      "HesabKolTitle": "حسابهای انتظامی به عهده شرکت",
      "GoroohHesabID": 10,
      "GoroohHesabCode": "91",
      "GoroohHesabTitle": "حسابهای انتظامی"
    },
    {
      "$id": "150",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 150,
      "HesabMoeeinCode": "911103",
      "HesabMoeeinTitle": "اسنادتضمینی بابت سفارشات",
      "HesabKolID": 38,
      "HesabKolCode": "9111",
      "HesabKolTitle": "حسابهای انتظامی به عهده شرکت",
      "GoroohHesabID": 10,
      "GoroohHesabCode": "91",
      "GoroohHesabTitle": "حسابهای انتظامی"
    },
    {
      "$id": "151",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 151,
      "HesabMoeeinCode": "911104",
      "HesabMoeeinTitle": "اسناد تضمینی بابت ضمانت نامه های گمرکی",
      "HesabKolID": 38,
      "HesabKolCode": "9111",
      "HesabKolTitle": "حسابهای انتظامی به عهده شرکت",
      "GoroohHesabID": 10,
      "GoroohHesabCode": "91",
      "GoroohHesabTitle": "حسابهای انتظامی"
    },
    {
      "$id": "152",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 152,
      "HesabMoeeinCode": "911105",
      "HesabMoeeinTitle": "اسناد تضمینی بابت تسهیلات مالی دریافتی",
      "HesabKolID": 38,
      "HesabKolCode": "9111",
      "HesabKolTitle": "حسابهای انتظامی به عهده شرکت",
      "GoroohHesabID": 10,
      "GoroohHesabCode": "91",
      "GoroohHesabTitle": "حسابهای انتظامی"
    },
    {
      "$id": "153",
      "$type": "<>f__AnonymousType0`9[[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib],[System.Int32, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], Mali.Server",
      "HesabMoeeinID": 153,
      "HesabMoeeinCode": "911201",
      "HesabMoeeinTitle": "طرف حساب انتظامی",
      "HesabKolID": 39,
      "HesabKolCode": "9112",
      "HesabKolTitle": "طرف حسابهای انتظامی",
      "GoroohHesabID": 10,
      "GoroohHesabCode": "91",
      "GoroohHesabTitle": "حسابهای انتظامی"
    }
  ]

